# srcs_dir has to be root for bazel proto/BUILD cc_grpc_library to work
srcs_dir: ./
srcs:
  - proto/bson.proto
  - proto/mongo.proto
output:
  - js:
      dir: dist/node
      options:
        import_style: commonjs
  - grpc-node:
      dir: dist/node
      custom: true
      plugin: grpc_tools_node_protoc_plugin
